INCLUDE_DIRS := Includes
CC 			 := g++
CFLAGS 		 := -I$(INCLUDE_DIRS)

OBJS		 := customErrorClass.o customErrorHandling.o
DEPS		 := $(INCLUDE_DIRS)/customErrorClass.h

.PHONY: clean all

all: customErrorClass.o customErrorHandling.o 